import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";

const run = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));

/** `git check-ignore` exits 1 for a path the repository would track. */
async function ignored(path: string): Promise<boolean> {
  try {
    await run("git", ["-C", repositoryRoot, "check-ignore", "-q", path]);
    return true;
  } catch {
    return false;
  }
}

describe("what tutorial/factory/ keeps", () => {
  it("tracks the learner's line, so their own work survives a mistake", async () => {
    for (const path of [
      "tutorial/factory/refactor/run.sh",
      "tutorial/factory/refactor/do.sh",
      "tutorial/factory/refactor/success.md",
      "tutorial/factory/refactor/commit.md",
      "tutorial/factory/refactor-do.sh"
    ]) {
      expect(await ignored(path), `${path} is the learner's work and should be tracked`).toBe(false);
    }
  });

  it("keeps the tutor's own state out, which belongs to one learner", async () => {
    for (const path of ["tutorial/.tutorial/session-20260825-120000-a1b2c3d4/events.jsonl", "tutorial/.tutorial/session-20260825-120000-a1b2c3d4/attempts.jsonl"]) {
      expect(await ignored(path), `${path} is engine state and should not be committed`).toBe(true);
    }
  });

  it("keeps out the data a run regenerates, which would otherwise churn every commit", async () => {
    // Every script writes its output to a .tmp/ beside itself, so one rule
    // covers both parts however many lines the learner ends up building.
    for (const path of [
      "tutorial/factory/refactor/.tmp/evidence.txt",
      "tutorial/factory/refactor/.tmp/validate-findings.txt",
      "tutorial/factory/refactor/.tmp/quality-before.txt",
      "tutorial/factory/refactor/.tmp/commit-message.txt",
      "tutorial/factory/refactor/.tmp/events/iteration-do.jsonl",
      "tutorial/factory/.tmp/refactor-quality-before.txt",
      "tutorial/factory/second-line/.tmp/anything.txt"
    ]) {
      expect(await ignored(path), `${path} is regenerated by a run and should not be committed`).toBe(true);
    }
  });

  it("ships the Part 2 seed, whose own .tmp/ is curriculum rather than a run's leavings", async () => {
    expect(await ignored("tutorial/docs/seeds/part-2/.tmp/refactor-quality-before.txt")).toBe(false);
  });
});
